spring:
  profiles:
    default: local
  datasource:
    url: jdbc:mysql://localhost:3306/mydb #데이터베이스 : mydb
    username: root
    password: '0000'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 내가만든 엔티티 정보가 db에 반영이 돼서 테이블이 생성되게끔 세팅을 해준다.(스키마 mydb만 직접 생성해두면 테이블은 서버 실행 시 알아서 생성)
      format_sql: true         # SQL 예쁘게
      highlight_sql: true      # 콘솔 하이라이트(선택)
    show-sql : true
  data:
    redis:
      host: localhost
      port: 6379 # Redis 기본 포트

logging:
  level:
    org.springframework.cache : trace # Redis 사용에 대한 로그가 조회되도록 설정
    org.hibernate.SQL: debug           # 실행된 SQL
    org.hibernate.orm.jdbc.bind: trace # 바인딩 값(?에 들어간 값)

server:
  port: 8090